"""Skill catalog taxonomy: 100 industries x 20 functions = 2000 generated
skills, plus a hand-curated generic pack that every business sees.

Skill slug = "{industry}-{function}" and is the resume/dedupe key for the
generation pipeline.
"""

# (slug, display label) — 100 industries
INDUSTRIES: list[tuple[str, str]] = [
    ("salon", "Hair & Beauty Salon"),
    ("barbershop", "Barbershop"),
    ("spa", "Spa & Massage Center"),
    ("nail-studio", "Nail Studio"),
    ("tattoo-studio", "Tattoo & Piercing Studio"),
    ("gym", "Gym & Fitness Center"),
    ("yoga-studio", "Yoga Studio"),
    ("dance-school", "Dance School"),
    ("martial-arts", "Martial Arts Academy"),
    ("personal-training", "Personal Training"),
    ("restaurant", "Restaurant"),
    ("cafe", "Cafe & Coffee Shop"),
    ("bakery", "Bakery"),
    ("cloud-kitchen", "Cloud Kitchen"),
    ("catering", "Catering Service"),
    ("food-truck", "Food Truck"),
    ("juice-bar", "Juice & Smoothie Bar"),
    ("sweet-shop", "Sweet Shop & Confectionery"),
    ("dental-clinic", "Dental Clinic"),
    ("medical-clinic", "Medical Clinic"),
    ("physiotherapy", "Physiotherapy Center"),
    ("diagnostics-lab", "Diagnostics Lab"),
    ("pharmacy", "Pharmacy"),
    ("veterinary", "Veterinary Clinic"),
    ("optician", "Optician & Eye Care"),
    ("ayurveda", "Ayurveda & Wellness Center"),
    ("mental-health", "Counselling & Therapy Practice"),
    ("nutritionist", "Nutritionist & Dietician"),
    ("real-estate", "Real Estate Agency"),
    ("property-management", "Property Management"),
    ("interior-design", "Interior Design Studio"),
    ("architecture", "Architecture Firm"),
    ("construction", "Construction Contractor"),
    ("home-cleaning", "Home Cleaning Service"),
    ("pest-control", "Pest Control Service"),
    ("plumbing", "Plumbing Service"),
    ("electrical", "Electrical Service"),
    ("appliance-repair", "Appliance Repair"),
    ("hvac", "AC & HVAC Service"),
    ("painting-service", "Painting & Renovation Service"),
    ("packers-movers", "Packers & Movers"),
    ("laundry", "Laundry & Dry Cleaning"),
    ("tailoring", "Tailoring & Alterations"),
    ("boutique", "Fashion Boutique"),
    ("jewellery", "Jewellery Store"),
    ("footwear", "Footwear Store"),
    ("electronics-store", "Electronics Store"),
    ("mobile-store", "Mobile Phone Store"),
    ("computer-repair", "Computer & Phone Repair"),
    ("furniture-store", "Furniture Store"),
    ("grocery", "Grocery & Kirana Store"),
    ("organic-store", "Organic & Health Store"),
    ("bookstore", "Bookstore & Stationery"),
    ("gift-shop", "Gift Shop"),
    ("toy-store", "Toy Store"),
    ("pet-store", "Pet Store"),
    ("pet-grooming", "Pet Grooming & Boarding"),
    ("florist", "Florist"),
    ("nursery", "Plant Nursery & Garden Center"),
    ("hardware-store", "Hardware & Building Materials"),
    ("auto-dealership", "Car & Bike Dealership"),
    ("car-service", "Car Service & Repair"),
    ("bike-service", "Bike Service & Repair"),
    ("car-wash", "Car Wash & Detailing"),
    ("car-rental", "Car & Bike Rental"),
    ("driving-school", "Driving School"),
    ("travel-agency", "Travel Agency"),
    ("tour-operator", "Tour Operator"),
    ("hotel", "Hotel & Guest House"),
    ("hostel-pg", "Hostel & PG Accommodation"),
    ("event-management", "Event Management"),
    ("wedding-planning", "Wedding Planning"),
    ("photography", "Photography Studio"),
    ("videography", "Videography & Film"),
    ("dj-entertainment", "DJ & Entertainment"),
    ("banquet-hall", "Banquet & Party Hall"),
    ("tutoring", "Tutoring & Coaching Center"),
    ("music-school", "Music School"),
    ("art-school", "Art & Craft Classes"),
    ("language-school", "Language School"),
    ("test-prep", "Exam & Test Prep Institute"),
    ("preschool", "Preschool & Daycare"),
    ("study-abroad", "Study Abroad Consultancy"),
    ("skill-training", "Vocational Skill Training"),
    ("law-firm", "Law Firm"),
    ("accounting", "Accounting & Tax Services"),
    ("insurance-agency", "Insurance Agency"),
    ("financial-advisory", "Financial Advisory"),
    ("hr-recruitment", "HR & Recruitment Agency"),
    ("marketing-agency", "Marketing & Ad Agency"),
    ("web-design", "Web & App Development Studio"),
    ("it-services", "IT Services & Support"),
    ("printing-press", "Printing & Signage"),
    ("courier", "Courier & Logistics"),
    ("security-services", "Security Services"),
    ("coworking", "Coworking Space"),
    ("dry-fruits", "Dry Fruits & Spices Store"),
    ("dairy", "Dairy & Milk Products"),
    ("agri-supplies", "Agri Supplies & Equipment"),
    ("handicrafts", "Handicrafts & Artisan Goods"),
]

# (slug, display label, brief for the generator) — 20 functions per industry
FUNCTIONS: list[tuple[str, str, str]] = [
    ("booking", "Appointment Booking", "collect preferred date/time and service, confirm against business hours, summarize the booking clearly"),
    ("lead-capture", "Lead Capture", "naturally collect name and phone/email from interested customers before the chat ends, without being pushy"),
    ("faq", "FAQ Expert", "answer common questions strictly from the business knowledge base; never invent facts"),
    ("pricing", "Pricing Guide", "share prices and packages from the knowledge base; never invent discounts or negotiate beyond stated policy"),
    ("availability", "Hours & Availability", "answer questions about opening hours, holidays, peak times, and current availability"),
    ("location", "Location & Directions", "help customers find the business: address, landmarks, parking, and travel directions"),
    ("complaints", "Complaint Handling", "de-escalate upset customers, apologize sincerely, gather details, promise human follow-up"),
    ("order-status", "Order & Request Status", "handle status enquiries: ask for reference details and set clear expectations on response time"),
    ("upsell", "Upsell & Cross-sell", "suggest one relevant add-on or upgrade per conversation, only after the main question is fully answered"),
    ("follow-up", "Follow-up & Reminders", "offer to have the business follow up, and remind customers about upcoming appointments or renewals"),
    ("cancellation", "Cancellation & Rescheduling", "handle cancellations and reschedules gracefully, state any policy, and offer alternative slots"),
    ("payments", "Payment Options", "explain accepted payment methods, advance/deposit rules, and refund policy from the knowledge base"),
    ("new-customer", "New Customer Welcome", "warmly onboard first-time customers: explain how the business works and what to expect on a first visit"),
    ("loyalty", "Loyalty & Offers", "explain current offers, memberships, or loyalty benefits from the knowledge base; encourage repeat visits"),
    ("feedback", "Review Collector", "after a positive resolution, politely ask the customer to leave a rating or review"),
    ("emergency", "Urgent Request Triage", "recognize urgent or emergency requests and immediately guide the customer to the fastest human contact"),
    ("product-info", "Service & Product Details", "explain the business's services/products in depth, comparing options to match customer needs"),
    ("eligibility", "Requirements & Eligibility", "explain prerequisites, documents, age limits, or preparation the customer needs before availing the service"),
    ("aftercare", "Aftercare & Support", "give post-service care guidance and handle 'what do I do now' questions after a purchase or visit"),
    ("handoff", "Human Handoff", "detect frustration or out-of-scope questions and smoothly offer to connect the owner or staff"),
]

# Hand-curated generic skills, enabled-by-default candidates for any business.
# These are inserted with industry='generic' and is_verified=true.
GENERIC_SKILLS: list[dict] = [
    {
        "slug": "generic-lead-capture",
        "name": "Lead Capture",
        "category": "sales",
        "description": "Never lose a potential customer — collects name and contact info naturally.",
        "prompt_snippet": "Before a conversation ends, if the customer has shown buying interest, naturally ask for their name and phone number or email so the business can follow up. Weave it into the conversation; never be pushy or robotic about it.",
    },
    {
        "slug": "generic-faq",
        "name": "FAQ Expert",
        "category": "support",
        "description": "Answers strictly from the business knowledge base — never guesses.",
        "prompt_snippet": "Answer questions using only the business knowledge base provided to you. If the answer is not there, say you will check with the team and offer to take the customer's contact details. Never invent prices, policies, or availability.",
    },
    {
        "slug": "generic-handoff",
        "name": "Human Handoff",
        "category": "support",
        "description": "Knows when to step aside and connect the customer to a human.",
        "prompt_snippet": "If the customer seems frustrated, asks something outside your knowledge, or explicitly asks for a human, apologize briefly and offer to connect them with the business owner or staff. Collect their contact details and a short summary of the issue so the handoff is smooth.",
    },
    {
        "slug": "generic-booking",
        "name": "Appointment Booking",
        "category": "booking",
        "description": "Collects date, time, and service preferences and confirms bookings clearly.",
        "prompt_snippet": "When a customer wants to book, collect the service they want, their preferred date and time, and their name and phone number. Check the business hours in the knowledge base before agreeing to a slot. End with a clear one-line summary of the booking details.",
    },
    {
        "slug": "generic-complaints",
        "name": "Complaint Handling",
        "category": "support",
        "description": "De-escalation mode: apologizes, listens, and promises human follow-up.",
        "prompt_snippet": "When a customer complains, never argue or get defensive. Apologize sincerely, ask for the details of what happened, and assure them the owner will personally follow up. Collect their contact information and summarize the complaint back to them.",
    },
    {
        "slug": "generic-pricing",
        "name": "Pricing Guide",
        "category": "sales",
        "description": "Shares pricing from the knowledge base and never invents discounts.",
        "prompt_snippet": "Share prices only from the business knowledge base. If a price is not listed, say you will confirm with the team rather than guessing. Never invent discounts or negotiate below listed prices unless the knowledge base explicitly allows it.",
    },
    {
        "slug": "generic-multilingual",
        "name": "Multilingual Auto-Reply",
        "category": "communication",
        "description": "Detects the customer's language and responds in it.",
        "prompt_snippet": "Detect the language the customer writes in and reply in that same language, keeping the same warm and professional tone. If they mix languages (e.g., Hinglish), mirror their style naturally.",
    },
    {
        "slug": "generic-upsell",
        "name": "Upsell & Cross-sell",
        "category": "sales",
        "description": "Suggests one relevant add-on per conversation, never pushy.",
        "prompt_snippet": "After fully answering the customer's question or completing their request, you may suggest at most one relevant add-on, upgrade, or complementary service from the knowledge base. Skip this entirely if the customer is complaining or frustrated.",
    },
    {
        "slug": "generic-feedback",
        "name": "Review Collector",
        "category": "growth",
        "description": "Asks happy customers for a review at the right moment.",
        "prompt_snippet": "When a conversation ends on a clearly positive note, politely ask the customer if they would leave a quick review or rating for the business, and share the review link if one exists in the knowledge base. Ask at most once per conversation.",
    },
    {
        "slug": "generic-hours",
        "name": "Hours & Location",
        "category": "support",
        "description": "Instantly answers where-are-you and when-are-you-open questions.",
        "prompt_snippet": "For questions about opening hours, address, or directions, answer directly from the knowledge base in one short message. Include a landmark or map link if available. If today might be a holiday, mention the customer should call ahead to confirm.",
    },
    {
        "slug": "generic-follow-up",
        "name": "Follow-up & Reminders",
        "category": "growth",
        "description": "Offers follow-ups and reminds customers about upcoming visits.",
        "prompt_snippet": "If a customer is undecided, offer to have the business follow up with them and collect the best time and contact method. If they mention an upcoming appointment, confirm the details and remind them of anything they need to bring or prepare.",
    },
    {
        "slug": "generic-urgent",
        "name": "Urgent Request Triage",
        "category": "support",
        "description": "Spots emergencies and routes them to a human immediately.",
        "prompt_snippet": "If a message indicates urgency or an emergency, skip the usual flow: immediately share the fastest way to reach a human (phone number from the knowledge base if available), keep your reply short, and flag that the owner should respond as soon as possible.",
    },
    {
        "slug": "generic-new-customer",
        "name": "New Customer Welcome",
        "category": "growth",
        "description": "Gives first-time customers a warm, clear introduction to the business.",
        "prompt_snippet": "When someone appears to be a first-time customer, warmly welcome them, give a one-paragraph overview of what the business offers, and ask one question to understand what they are looking for. Keep it inviting, not salesy.",
    },
    {
        "slug": "generic-cancellation",
        "name": "Cancellation & Rescheduling",
        "category": "booking",
        "description": "Handles cancellations gracefully and always offers an alternative.",
        "prompt_snippet": "When a customer wants to cancel or reschedule, respond graciously without guilt-tripping. State the cancellation policy if it exists in the knowledge base, and always offer two or three alternative slots or options before closing the conversation.",
    },
    {
        "slug": "generic-payments",
        "name": "Payment Options",
        "category": "sales",
        "description": "Explains accepted payment methods, deposits, and refund policy.",
        "prompt_snippet": "Explain accepted payment methods (UPI, cards, cash, etc.) and any advance or deposit requirements exactly as stated in the knowledge base. For refund questions, quote the policy; if there is none, promise a follow-up from the owner.",
    },
    {
        "slug": "generic-product-info",
        "name": "Service & Product Details",
        "category": "sales",
        "description": "Explains offerings in depth and helps customers compare options.",
        "prompt_snippet": "When asked about services or products, explain them clearly using the knowledge base, and help the customer compare options based on their stated needs and budget. Recommend the best fit and say why in one sentence.",
    },
    {
        "slug": "generic-aftercare",
        "name": "Aftercare & Support",
        "category": "support",
        "description": "Handles post-purchase questions and care instructions.",
        "prompt_snippet": "For customers who have already purchased or visited, answer aftercare and usage questions patiently using the knowledge base. If the issue sounds like a defect or service failure, switch to complaint handling and offer a human follow-up.",
    },
    {
        "slug": "generic-loyalty",
        "name": "Loyalty & Offers",
        "category": "growth",
        "description": "Promotes current offers and membership benefits accurately.",
        "prompt_snippet": "If the knowledge base lists current offers, memberships, or loyalty programs, mention the most relevant one when a customer asks about prices or visits repeatedly. Quote terms exactly; never invent or extend an offer.",
    },
    {
        "slug": "generic-eligibility",
        "name": "Requirements & Eligibility",
        "category": "support",
        "description": "Tells customers what they need before availing a service.",
        "prompt_snippet": "When relevant, proactively tell customers what they need to bring, prepare, or qualify for before availing the service — documents, age limits, prerequisites, or preparation steps — using the knowledge base as the source of truth.",
    },
    {
        "slug": "generic-concise",
        "name": "Concise Replies",
        "category": "communication",
        "description": "Keeps every reply short, scannable, and chat-friendly.",
        "prompt_snippet": "Keep replies short and chat-friendly: two to four sentences for simple questions, short bullet lists only when comparing options. Never send long paragraphs in a messaging chat.",
    },
]
